"""Load the declarative enrichment artifacts: rubrics, guardrails, vocabulary.

Rubrics and `guardrails.yaml` are packaged inside `xbrain` so they ship in the
wheel. `data/vocab.yaml` is generated by the `vocab` stage and read by `enrich`.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

from xbrain.models import Topic

# Case-insensitive sniff for any leftover `{...language...}` placeholder
# after substitution — catches typos like `{Language}` or `{LANGUAGE}` that
# str.replace("{language}", ...) would silently miss.
_LEFTOVER_PLACEHOLDER = re.compile(r"\{[^}]*language[^}]*\}", re.IGNORECASE)

_PKG = Path(__file__).resolve().parent
_RUBRICS_DIR = _PKG / "rubrics"
_GUARDRAILS = _PKG / "guardrails.yaml"

# Max characters of linked-article body passed to an executor. Shared by the
# `api` executor prompt and the worksheet export so both truncate identically.
ARTICLE_CHAR_LIMIT = 4000


def load_rubric(name: str, *, language: str | None = None) -> str:
    """Return the text of `rubrics/rubric-<name>.md`.

    When `language` is set, any `{language}` placeholder in the rubric is
    substituted with the given value (e.g. ``"English"``). When ``None``
    (tests, manual inspection), the placeholder is preserved verbatim.

    Substitution is plain `str.replace`; rubrics without a placeholder are
    returned unchanged regardless of `language`.

    Defensive check: when `language` is provided, the returned text must not
    contain a literal `{language}` (catches typos like `{Language}` that
    would silently survive substitution and ship the placeholder to the LLM).
    """
    path = _RUBRICS_DIR / f"rubric-{name}.md"
    if not path.exists():
        raise FileNotFoundError(f"Rubric not found: {path}")
    text = path.read_text(encoding="utf-8")
    if language is not None:
        text = text.replace("{language}", language)
        leftover = _LEFTOVER_PLACEHOLDER.search(text)
        if leftover is not None:
            raise ValueError(
                f"Rubric {name!r} contains an unresolved placeholder "
                f"{leftover.group()!r}. The supported form is `{{language}}` "
                f"(lowercase); check for case-variant typos."
            )
    return text


def load_guardrails() -> dict:
    """Return the parsed `guardrails.yaml`."""
    if not _GUARDRAILS.exists():
        raise FileNotFoundError(f"guardrails.yaml not found: {_GUARDRAILS}")
    return yaml.safe_load(_GUARDRAILS.read_text(encoding="utf-8")) or {}


def load_vocab(path: Path) -> list[Topic]:
    """Load the topic vocabulary; an empty list if the file does not exist."""
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return [Topic(**entry) for entry in data.get("topics", [])]


def save_vocab(topics: list[Topic], path: Path) -> None:
    """Persist the topic vocabulary as YAML."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"topics": [t.model_dump() for t in topics]}
    path.write_text(
        yaml.safe_dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
