"""Load the declarative enrichment artifacts: rubrics, guardrails, vocabulary.

Rubrics and `guardrails.yaml` are packaged inside `xbrain` so they ship in the
wheel. `data/vocab.yaml` is generated by the `vocab` stage and read by `enrich`.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from xbrain.models import Topic

_PKG = Path(__file__).resolve().parent
_RUBRICS_DIR = _PKG / "rubrics"
_GUARDRAILS = _PKG / "guardrails.yaml"

# Max characters of linked-article body passed to an executor. Shared by the
# `api` executor prompt and the worksheet export so both truncate identically.
ARTICLE_CHAR_LIMIT = 4000


def load_rubric(name: str) -> str:
    """Return the text of `rubrics/rubric-<name>.md`."""
    path = _RUBRICS_DIR / f"rubric-{name}.md"
    if not path.exists():
        raise FileNotFoundError(f"Rubric not found: {path}")
    return path.read_text(encoding="utf-8")


def load_guardrails() -> dict:
    """Return the parsed `guardrails.yaml`."""
    if not _GUARDRAILS.exists():
        raise FileNotFoundError(f"guardrails.yaml not found: {_GUARDRAILS}")
    return yaml.safe_load(_GUARDRAILS.read_text(encoding="utf-8")) or {}


def load_vocab(path: Path) -> list[Topic]:
    """Load the topic vocabulary; an empty list if the file does not exist."""
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return [Topic(**entry) for entry in data.get("topics", [])]


def save_vocab(topics: list[Topic], path: Path) -> None:
    """Persist the topic vocabulary as YAML."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"topics": [t.model_dump() for t in topics]}
    path.write_text(
        yaml.safe_dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
